### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '$refs')

### ISSUE THREAD

**Issue by joaomarcosfluxxer** [zanmato/vue3-treeselect#1]
```
<template>
  <Treeselect
    v-model="value"
    multiple="true"
    :options="options"
    placeholder="Select your favourite(s)..."
  />
  <TreeselectValue :value="value" />
</template>


<script setup>
import Treeselect from "@zanmato/vue3-treeselect"
import "@zanmato/vue3-treeselect/dist/vue3-treeselect.min.css"
const value = ref([])

const options =  ref([
  {
    id: "fruits",
    label: "Fruits",
    children: [
      {
        id: "apple",
        label: "Apple 🍎",
        isNew: true,
      },
      {
        id: "grapes",
        label: "Grapes 🍇",
      },
      {
        id: "pear",
        label: "Pear 🍐",
      },
      {
        id: "strawberry",
        label: "Strawberry 🍓",
      },
      {
        id: "watermelon",
        label: "Watermelon 🍉",
      },
    ],
  },
  {
    id: "vegetables",
    label: "Vegetables",
    children: [
      {
        id: "corn",
        label: "Corn 🌽",
      },
      {
        id: "carrot",
        label: "Carrot 🥕",
      },
      {
        id: "eggplant",
        label: "Eggplant 🍆",
      },
      {
        id: "tomato",
        label: "Tomato 🍅",
      },
    ],
  },
])
</script>
```

vue: **3.4.5**
error: **Uncaught TypeError: Cannot read properties of undefined (reading '$refs')
    at Proxy.getValueContainer (@zanmato_vue3-treeselect.js?t=1704739889263&v=d5cb4515:731:37)
    at Proxy.<anonymous> (@zanmato_vue3-treeselect.js?t=1704739889263&v=d5cb4515:739:79)
    at Proxy.<anonymous> (@zanmato_vue3-treeselect.js?t=1704739889263&v=d5cb4515:90:23)
    at callWithErrorHandling (chunk-UO42OTED.js?v=d5cb4515:1634:18)
    at callWithAsyncErrorHandling (chunk-UO42OTED.js?v=d5cb4515:1642:17)
    at HTMLDivElement.invoker (chunk-UO42OTED.js?v=d5cb4515:10159:5)**

**Comment by zanmato** [comment]
It seems like your example is incomplete, it is missing imports for `ref` and `TreeselectValue`?

**Comment by KushalNaral** [comment]
Same issue arises here even though the steps from the documentation are followed
