### ISSUE TITLE
append-to-body does not work

### ISSUE THREAD

**Issue by jesse-s** [zanmato/vue3-treeselect#4]
When setting the option :append-to-body="true", an error is thrown and you cannot interact with the instance:

`Uncaught (in promise) TypeError: e2 is undefined`

**Comment by zanmato** [comment]
Please try `0.4.1-dev`

**Comment by jesse-s** [comment]
Works, thanks for the quick fix!

**Comment by jesse-s** [comment]
Still getting a lot of weird errors when the option is set to true:

`Cannot read properties of null (reading 'querySelector')`
`Cannot read properties of null (reading 'getBoundingClientRect')`
`Cannot read properties of null (reading 'id')`

These errors do not occur when the option is set to false.

**Comment by jesse-s** [comment]
I tried replicating the errors in [playcode](https://playcode.io/2188911) but cannot seem to reproduce it there, weird. When clearing the input field on my production website, this line seems to give troubles in treeselectMixin.js:

`this.menu.current = node.id;`

For example when selecting all text and pressing backspace, `node` seems to be null most of the times.

The `querySelector` and `getBoundingClientRect` errors happen when visitors on a bit older Android devices use the library. Haven't been able to reproduce that as well, sorry about that.

BTW: In the playcode example you can see that #search-prompt-tip does not show.

**Comment by zanmato** [comment]
Couldn't replicate it either, but if you know which Android device it is then I could try replicating it in Android Studio

**Comment by jesse-s** [comment]
Tried it in an several older Android emulators and couldn't replicate it. Consider this bug fixed!
